include: package:flutter_lints/flutter.yaml

linter:
  rules:
    require_trailing_commas: true
    always_use_package_imports: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**.dart"
  errors:
    invalid_annotation_target: ignore
    body_might_complete_normally_nullable: ignore