name: notion_client
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  flutter_svg: ^0.23.0+1

  #Navigation
  auto_route: ^3.2.1

  #Network
  retrofit: ^2.2.0
  dio: ^4.0.1

  #DI
  provider: ^6.0.1

  #Architecture
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3

  #Utils
  intl: ^0.17.0
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0
  json_annotation: ^4.3.0
  rxdart: ^0.27.2
  spider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.1
  json_serializable: ^6.0.1
  retrofit_generator: ^2.2.0
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/images/jpg/
flutter_intl:
  enabled: true
